[build]
  command = "yarn build && yarn export"
  publish = "out/"

[build.environment]
  CMS_GHOST_API_URL = "https://cms.gotsby.org"
  CMS_GHOST_API_KEY = "387f956eaa95345f7bb484d0b8"

[[plugins]]
  package = "netlify-plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
